name: play_ground
description: "Para teste de códigos é packages"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smb_connect: ^0.0.7
  zsdk: ^3.2.0+3
  #printing: ^5.13.4
  #pdf: ^3.11.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
